"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
import datetime
from setuptools import setup

APP = ['live.py']
VERSION = "0.0.1"
copyright = 'Copyright {} NOTAG.'.format(datetime.datetime.now().year)
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '10.12.0',
        'CFBundleIdentifier': 'cn.notag.live',
        'NSHumanReadableCopyright': copyright,
        'CFBundleShortVersionString': str(VERSION),
        'CFBundleVersion': str(VERSION),
    },
    'excludes': ['PIL', 'tkinter'],
    'packages': ['rumps', 'app'],
    'iconfile': os.path.abspath('app/assets/icon.icns')
}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    py_modules=[]
)
